diff_drive_controller:
  ros__parameters:
    wheel_base: 0.19685
    wheel_radius: 0.03175
    max_linear_vel: 0.55
pid_controller:
  ros__parameters:
    kp: 8.0
    ki: 1.2
    kd: 0.9
    pid_rate: 0.05
velocities:
  ros__parameters:
    wheel_radius: 0.03175
pose_estimator:
  ros__parameters:
    wheel_base: 0.19685
    wheel_radius: 0.03175
    ticks_per_rev: 40
    refresh_rate: 0.1
    meters_per_tick: 0.0049873

    

