diff_drive_controller:
  ros__parameters:
    wheel_base: 0.2200
    wheel_radius: 0.032499
    max_linear_vel: 0.4
    max_angular_vel: 0.75 
pid_controller:
  ros__parameters:
    kp: 1.0
    ki: 0.4
    kd: 0.0
    pid_rate: 0.05
velocities:
  ros__parameters:
    wheel_radius: 0.032499
wheel_odometry:
  ros__parameters:
    wheel_base: 0.2200
    wheel_radius: 0.032499
    ticks_per_rev: 40
    refresh_rate: 0.03
    meters_per_tick: 0.0051049
    frame_id: "odom"
    child_frame_id: "base_link"
    

