diff_drive_controller:
  ros__parameters:
    wheel_base: 0.19685
    wheel_radius: 0.03175
    max_linear_vel: 0.3
pid_controller:
  ros__parameters:
    kp: 2
    ki: 1.2
    kd: 0.9
    pid_rate: 0.05
velocities:
  ros__parameters:
    wheel_radius: 0.03175
wheel_odometry:
  ros__parameters:
    wheel_base: 0.19685
    wheel_radius: 0.03175
    ticks_per_rev: 40
    refresh_rate: 0.03
    meters_per_tick: 0.0049873
    frame_id: "odom"
    child_frame_id: "base_link"
    

